apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocolate-doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chocolate-doom
  template:
    metadata:
      labels:
        app: chocolate-doom
    spec:
      containers:
      - name: chocolate-doom
        image: simply007/chocolate-doom:latest
        ports:
        - containerPort: 6080
        readinessProbe:
          httpGet:
            path: /vnc.html
            port: 6080
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chocolate-doom-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 6080
    protocol: TCP
    name: novnc
  selector:
    app: chocolate-doom
