apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-doom-deployment
  labels:
    app: http-doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-doom
  template:
    metadata:
      labels:
        app: http-doom
    spec:
      containers:
      - name: http-doom
        image: mattipaksula/http-doom:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
---
---
apiVersion: v1
kind: Service
metadata:
  name: http-doom-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: novnc
  selector:
    app: http-doom
