apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocolate-doom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chocolate-doom
  template:
    metadata:
      labels:
        app: chocolate-doom
    spec:
      containers:
        - name: chocolate-doom
          image: simply007/chocolate-doom:latest
          ports:
            - containerPort: 6080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            tcpSocket:
              port: 6080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chocolate-doom-service
spec:
  type: LoadBalancer
  ports:
    - port: 6080
      targetPort: 6080
      protocol: TCP
      name: novnc
  selector:
    app: chocolate-doom
